### ISSUE TITLE
size() method on Response class specifies :number as return type, but returns an object instead

### ISSUE THREAD

**Issue by independentvar** [postmanlabs/postman-collection#1107]
Size method in Response class specifies to return a number:
https://github.com/postmanlabs/postman-collection/blob/22f1204fefd02b05c90e13e5d4bb3b29330cd2ac/types/index.d.ts#L2018-L2021

When I call this method I get anonymous object with these properties instead: 
```js
{
  body: number
  header: number
  total: number
}
```
I can also see that an object is returned instead of a number when I look at size method implementation:
https://github.com/postmanlabs/postman-collection/blob/22f1204fefd02b05c90e13e5d4bb3b29330cd2ac/lib/collection/response.js#L470-L524

Typescript definitions needs to be updated with a correct type instead.

**Comment by codenirvana** [comment]
Thank you for reporting this issue but since v3.6.9, these auto-generated type declarations will not be used.

Refer: https://github.com/postmanlabs/postman-collection/issues/602#issuecomment-753507973
