### ISSUE TITLE
"missing field `name` at ... " error when transpiling Collection that already includes [info] object

### ISSUE THREAD

**Issue by WilliamBerryiii** [postmanlabs/postman-collection#1127]
https://github.com/postmanlabs/postman-collection/blob/6f7cf5e00bb4f7242e54726e6835550f277b7828/lib/collection/collection.js#L193

I have a postman collection which already includes an [info] object. The above function will nuke the info object as it converts the collection to JSON. I believe (naively) that wrapping the call with a 'hasOwnProperty' should avoid the issue; but I'm not confident of forward/backward compatibility against the postman schema changes over time.

Will make a PR, but I'm also conscious that the change may need more robust error handling for cases I'm not familiar with.

**Comment by codenirvana** [comment]
@WilliamBerryiii Sorry for the delayed response and thank you for your contribution.
I've updated the failing CI tests in your PR.

Can you give more information about your use-case? Are you trying to add/preserve your custom props in the `info` object?

**Comment by WilliamBerryiii** [comment]
I was attempting to do so (mainly the "name" field in the info element) ... but I elected to take another approach and just defined a collection.name value (root) which does propagate correctly. Maybe we just nuke my change unless you see value in it.
