### ISSUE TITLE
Fix vulnerabilities

### ISSUE THREAD

**Issue by vaagnavanesyan** [postmanlabs/postman-collection#1170]
I've noticed that running `npm audit` finds 162 vulnerabilities with different levels and `npm audit fix` resolves 158 of them.

Should I prepare PR with dependencies upgrade? I also can perform force upgrading of all dependencies and fix consequences to make tests green.

**Comment by codenirvana** [comment]
Thanks for testing this but `npm audit` is actually misleading and in most case just produce unnecessary noise.

The 162 vulnerabilities are from dev-dependencies and for now, we are only focusing on the ` npm audit --production` results.
