### ISSUE TITLE
Can we bump sanitize-html dependency to address this CVE?

### ISSUE THREAD

**Issue by gone-skiing** [postmanlabs/postman-collection#1181]
https://github.com/advisories/GHSA-mjxr-4v3x-q3m4

**Comment by gone-skiing** [comment]
I am happy to spin up a PR...

**Comment by gone-skiing** [comment]
@codenirvana here is a PR to bump the dependency if your team has a minute...
https://github.com/postmanlabs/postman-collection/pull/1183

**Comment by codenirvana** [comment]
Fixed in v4.

**Comment by delixfe** [comment]
@codenirvana: could you also create a patch for v3?
Not everyone will like to update to a new major version for a security fix.

**Comment by codenirvana** [comment]
@delixfe Sure but can you also check [the changelog](https://github.com/postmanlabs/postman-collection/blob/develop/CHANGELOG.yaml#L3) to verify the breaking changes?

**Comment by delixfe** [comment]
@codenirvana Actually, I think many of us would prefer not to have to check those. That was the reason I have asked :). 
Now I did read them and I won't be affected by the breaking changes so I can easily upgrade to v4.
