### ISSUE TITLE
Missing apikey Auth Type

### ISSUE THREAD

**Issue by zachwhaley** [postmanlabs/postman-collection#1192]
I'm looking to implement the [API Key Authorization helper](https://learning.postman.com/docs/sending-requests/authorization/#api-key) with the postman collection SDK, but it does not seem to have an auth type that looks like this.

I can also see the apikey auth type in the postman schema https://schema.postman.com/collection/json/v2.1.0/draft-07/collection.json

https://github.com/postmanlabs/postman-collection/blob/develop/lib/schema/auth.json#L9

**Comment by codenirvana** [comment]
Thanks for reporting this but schema is moved to [a separate repository](https://github.com/postmanlabs/schemas) and no longer maintained in this repository.
