### ISSUE TITLE
Collection variables do not seem to work

### ISSUE THREAD

**Issue by YemSalat** [postmanlabs/postman-collection#125]
I am trying to import a collection with some variables pre-set in it.
Here is the part of my .postman_collection that does that:
```
{
  "variable": [
    {
      "id": "hostUrl",
      "name": "hostUrl",
      "value": "__TEST__",
      "type": "string"
    }
  ]
...
```

And then in the url I have: `{{ hostUrl }}/foo/bar`

But when I submit the request in postman - it does not render the variable value - instead it encodes the curly brackets and spaces: `http://%7B%7B%20hostUrl%20%7D%7D/foo/bar`

Any idea what might be wrong here?

PS I am using postman collection v2 format

**Comment by kunagpal** [comment]
Hey @YemSalat This issue is related to the Postman app, please head over to https://github.com/postmanlabs/postman-app-support/issues for your support query. Thanks!

**Comment by YemSalat** [comment]
Thanks @kunagpal, reposted over there: https://github.com/postmanlabs/postman-app-support/issues/2336

**Comment by kunagpal** [comment]
👍
