### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by yn-codes** [postmanlabs/postman-collection#138]
**Stakeholder** : Postman Client User (Developer)
**Problem/Need** : To be able to organize and re-organize related collections (sometimes already organized into folders) easily 
**Solution** : A drag and drop feature in the Postman Client where collections (in folders) can be easily dragged and dropped into other folders (instead of only a single API within a collection)

**Comment by a85** [comment]
@yn-codes This belongs here: github.com/postmanlabs/postman-app-support/issues. We have this on our roadmap. We will have an ETA soon.

**Comment by yn-codes** [comment]
@a85 , thank you.

**Comment by yn-codes** [comment]
Closing this issue, since it should be elsewhere + you already have it in your roadmap.
