### ISSUE TITLE
Content-Type charset=UTF-8 invalid

### ISSUE THREAD

**Issue by TonyYule** [postmanlabs/postman-collection#154]
Content-Type:application/x-www-form-urlencoded;charset=UTF-8
I want to set the default encoding to utf-8 but when sending a request is not utf-8

**Comment by czardoz** [comment]
@TonyYule, do open an issue at https://github.com/postmanlabs/postman-app-support/issues :)

This particular repository is for tracking bugs in the `postman-collection` codebase.
