### ISSUE TITLE
Run in Postman button fuzzy on retina displays

### ISSUE THREAD

**Issue by robertkern** [postmanlabs/postman-collection#206]
I apologise in advance as I'm sure this isn't the right place to add this - I couldn't find a suitable repo (the docs repo doesn't have issues enabled).

The "Run in Postman" button is not high-res so looks fuzzy on high-res/retina displays. This is when using the Share option in Postman to generate the javascript to display a Run in Postman button.

The background image should be double-sized and use css to reduce size by 50%. We could probably fix this ourselves using our own css, but I think it should be handled by Postman.

**Comment by kunagpal** [comment]
@robertkern Is this still a concern with Postman `v4.10.5`? If so, please open up an issue at https://github.com/postmanlabs/postman-app-support/issues/new
