### ISSUE TITLE
Test Plan that errors out is shown as 'All Passed' in Collection Runner

### ISSUE THREAD

**Issue by BrendanJMurray** [postmanlabs/postman-collection#212]
I found this while running a test plan using the wrong environment. The plan errors out before it can run, but in the GUI's `Previous Runs` history it appears as if the test plan had no errors.

This is an edge case but the phrase `All Passed` and the color green are definitely unexpected behavior here.

![failingcollectionpassing](https://cloud.githubusercontent.com/assets/20906544/20314719/23871998-ab29-11e6-8767-1b96b1a1d244.gif)

**Comment by kunagpal** [comment]
@BrendanJMurray if this issue persists with Postman `v4.10.5`, please open an issue at https://github.com/postmanlabs/postman-app-support/issues/new
