### ISSUE TITLE
Exporting a Run as JSON

### ISSUE THREAD

**Issue by kbajpai** [postmanlabs/postman-collection#224]
In the image Gelatin (A) is a collection with 2 folders:

1. ALL
2. Registered

When I run the TEST it goes fine & runs only REGISTERED, but when I try to export REGISTERED only from the sidebar of the RUNNER, the exported JSON file contains ALL too. I only want to have REQUESTS from REGISTERED only to be exported as JSON to run on newman.

![collections](https://cloud.githubusercontent.com/assets/813554/20646778/15be04de-b448-11e6-8888-065be3a9748f.png)

**Comment by kunagpal** [comment]
@kbajpai The exported JSON run will always be a complete representation of the collection run for the purposes of completeness. To run a specific folder within Newman, you can export the collection (and other related globals and environment files), and run the collection like so:
```bash
newman run collection.json -e env.json -g globals.json -f <Name of the folder to be run>
```
