### ISSUE TITLE
Import collections

### ISSUE THREAD

**Issue by annguyen209** [postmanlabs/postman-collection#228]
When I do import collections from a folder, some collections already exist and a message box displays to ask me Replace or Import as Copy. I have to click so many times repeatedly because it asks for every single collection. It is more helpful when we have an option that says "Do it for all" to apply for all actions.

Regards,
An.

**Comment by kunagpal** [comment]
@annguyen209 I've opened up a dedicated feature request, you can track it's progress here: https://github.com/postmanlabs/postman-app-support/issues/2892
