### ISSUE TITLE
Allow sub folders for collections

### ISSUE THREAD

**Issue by lordmilutin** [postmanlabs/postman-collection#230]
How difficult is it to add sub folders to collections?

**Comment by kunagpal** [comment]
@lordmilutin Newman already supports multi-level folders, we're in the process of ironing out multi-level folder support in the Postman app.

**Comment by kunagpal** [comment]
As of Postman 5.1.2, folders can be nested in collections. https://www.getpostman.com/apps

**Comment by Tset-Noitamotua** [comment]
And how can we run a collection inside postman subfolder from newman?

e.g. I have a collection `foo.json`  which has folder `parent fold` with subfolder `sub fold`. Note that there are spaces in the folder names.

I've tried without success:
`newman run foo.json --folder "parent fold/sub fold" -e my_env.json`
 `newman run foo.json --folder "parent fold"/"sub fold" -e my_env.json`
`newman run foo.json --folder "parent fold\sub fold" -e my_env.json`

**Comment by kunagpal** [comment]
You can specify the folder name directly, like so:
```shell
newman run foo.json --folder "sub fold" -e my_env.json
```

**Comment by Tset-Noitamotua** [comment]
indeed ... thanks for 'speed-of-light'-feedback :)

But what if there is a subfolder with same name in another folder?

**Comment by kunagpal** [comment]
In that case, the last match will be considered for execution. The logic for the same can be found here: https://github.com/postmanlabs/postman-runtime/blob/develop/lib/runner/index.js#L48

**Comment by mijorus** [comment]
This sucks. 
I have literally just lost one hour trying to debug this.

My collection structure is something like 
```
collection
        --  folder1
                  -- folder1tests
```

and I need to run newman with --folder="folder1tests" ( instead of --folder="folder1/folder1tests".
