### ISSUE TITLE
How to get the saved response into testscript?

### ISSUE THREAD

**Issue by SMohamedMubarish** [postmanlabs/postman-collection#234]
Hi,
  I am using Postman for RestApi Testing. I am trying to compare JSON response structure with the old JSON response to identify any breakage. For that I need the saved response (previously saved response) to compare with the current response. how to get the saved response into testscript, so that I can use that old saved response to check the structure change? or any other way is appreciable?

Thanks in Advance!

**Comment by kunagpal** [comment]
@SMohamedMubarish Although there is no way to use previously saved responses (yet), you can save the expected response to a variable within your request test scripts. You can then compare the expected and actual response from your request.
