### ISSUE TITLE
How can I get the input parameters inside testscripts?

### ISSUE THREAD

**Issue by SMohamedMubarish** [postmanlabs/postman-collection#235]
I am trying to do **input validation** ( whether the input and output parameter values are equal) in postman. For example, if I am sending payload as {"name":"test"} and if I am getting response as {"name" : "test"}, I  need to check the key "name" in response is same as payload (i.e) test, **dynamically**. for that I need to get input parameters (query and payload) inside testscripts. How  can i get the input parameters inside testscripts?

Thanks in Advance!

**Comment by kunagpal** [comment]
@SMohamedMubarish Assuming that your endpoint returns a response in the following form:
```json
{
    "name": "test"
}
```

You can use the following snippet to test request response equivalence:
```javascript
var reqBody = JSON.parse(request.data),
    resBody = JSON.parse(responseBody);

tests["Body was POSTed correctly"] = reqBody.name === resBody.name;
```

Here, `request` and `responseBody` are inbuilt objects.
