### ISSUE TITLE
How to use Data variables in raw XML post body in collection?

### ISSUE THREAD

**Issue by pandiankaruppaiah** [postmanlabs/postman-collection#285]
I have created 2 XML post requests in collection and each post request will return XML response. I tried to form chain request from response returned  in first request. I captured few values from response and tried to pass those in XML POST body of second request but could not. I tried with {{variable}} but it is not working. i am posting as application/xml content type.
actual raw XML : 
<source><Team Date=**"23/2/2017"**></source>
How i want:
<source><Team Date=**variable holding values from response**></source>

**Comment by pandiankaruppaiah** [comment]
If xml is having attribute like Date = "23/2/2017".  i want to replace that value with previous response.

**Comment by kunagpal** [comment]
Consider the following XML response:
```xml
<?xml version="1.0" encoding="utf-8"?>
<res>
<key Date="23/2/2017"></key>
</res>
```

Then, the following snippet can be used to replace the date with the desired value:
```
// 1st request
var json = xml2Json(responseBody);
postman.setEnvironmentVariable("date", json.res.key.$.Date);
```

Then, the post body of your second request would look like:
```xml
<?xml version="1.0" encoding="utf-8"?>
<res>
<key Date="{{date}}"></key>
</res>
```
