### ISSUE TITLE
Saving Response should save the request that generates the response

### ISSUE THREAD

**Issue by nsasikumar** [postmanlabs/postman-collection#330]
Saving responses generated by different request data should save the data that generated the request as well. If I save responses for 200 and 404 error codes, I don't want the sample request in the Docs to be the same for both responses.

**Comment by a85** [comment]
I think this happens already. If not, it's a bug.

**Comment by nsasikumar** [comment]
It seemed like it should, so I didn't investigate too closely and only noticed after I saved a bunch of responses. 

Here is an example of the same end point with two different responses. 

In the first one, both the request and the response should be an array of strings and they both are.

In the second, both the request and response should be an array of objects. You can see that the response is an array of objects as expected, but the request is an array of strings (should be an array of objects). 

 As you can see the request data for both the responses are the same even though they shouldn't be. 

![2](https://cloud.githubusercontent.com/assets/4837653/24771294/13fa3f7e-1adb-11e7-8bc8-dd940037adc7.png)
![1](https://cloud.githubusercontent.com/assets/4837653/24771295/13fc3c5c-1adb-11e7-86cd-09f6efa17334.png)

**Comment by shamasis** [comment]
I see this already being done. Closing it. Please reopen if otherwise.
