### ISSUE TITLE
Executing a request n times with different input values in json body from previous request

### ISSUE THREAD

**Issue by antlopnav** [postmanlabs/postman-collection#336]
I have two requests (**descargaListaEncargo** and **descargaEncargo**). In the first request, I get an array with idEncargo which I set in global variable. In second request, I get info about idEncargo which is passed as input parameter in body

Body for **descargaEncargo**:

```
{
   "idEncargo":{{encargo}} 
}
```
In pre-request script for this request, I put the next code:

```
var listaEncargos = JSON.parse(postman.getGlobalVariable("listaEncargo"));

for (var i = 0; i < listaEncargos.length; i++) {
    postman.setGlobalVariable("encargo", listaEncargos[i]);
} 
```
Variable listaEncargo is set in previous request **descargaListaEncargo** like an array of idEncargo. To execute **descargaEncargo**, request only takes the last value in array.

Somebody could help me?

**Comment by shamasis** [comment]
Can you report this in postman-app-support repository. This repository is for postman collection sdk.
