### ISSUE TITLE
ItemGroup.add does not properly understand what is being added

### ISSUE THREAD

**Issue by czardoz** [postmanlabs/postman-collection#35]
If someone has already created an `ItemGroup`, and tries to add it, the SDK coerces the `ItemGroup` to an `Item` because the `ItemGroup` has a property `items` while the SDK checks for `Item`

Fix should go here:
https://github.com/postmanlabs/postman-collection/blob/4db12bb343bda0ff09b707957f5108c4f30380e6/lib/collection/item-group.js#L217

**Comment by shamasis** [comment]
Working on it. Possible solution:

- add `.addItem` and `addItemGroup` sugar functions to `ItemGroup`
- create a pseudo constructor called`ItemOrGroup` but that which constructs and returns an `Item` or `ItemGroup`

**Comment by kunagpal** [comment]
Resolved in #324
