### ISSUE TITLE
Support "disabled" in query params

### ISSUE THREAD

**Issue by WoLfulus** [postmanlabs/postman-collection#415]
I'm trying to generate a collection with several `disabled by default` query parameters, but passing `disabled` to query params doesn't actually disables them.

Looking at the exported JSON and the source code, only `key` and `value`  are present.

Is there a reason why `disabled` wasn't included in query params like headers?

**Comment by kunagpal** [comment]
This a fix for this bug has been added in #429, and has now been released. Feel free to reopen if you're facing difficulties. Thanks! 😄
