### ISSUE TITLE
copy the real url string instead of the Environment/Global variables

### ISSUE THREAD

**Issue by imwower** [postmanlabs/postman-collection#420]
hi, when we use Environment/Global variables, the url is presented like:
`www.google.com/foo/{{profile}}`
while the `{{profile}}` variable stands for `develop`,
so, could postman add a feature or function which can copy the exactly url string:
`www.google.com/foo/develop`
 instead of :
`www.google.com/foo/{{profile}}`

thanks.

![qq 20170724182819](https://user-images.githubusercontent.com/1744486/28519627-f1571360-709e-11e7-95da-d254dc18adec.png)

**Comment by kunagpal** [comment]
@imwower Please create a feature request here: https://github.com/postmanlabs/postman-app-support/issues/new, this issue tracker is for the Postman Collection SDK. Thanks!
