### ISSUE TITLE
Error in example code for Item constructor

### ISSUE THREAD

**Issue by georgejdli** [postmanlabs/postman-collection#478]
For this example code in Item doc:
`var Collection = require('postman-collection').Collection,
    Item = require('postman-collection').Item,
    myCollection;

myCollection = new Collection({
    "item": [{
        "id": "my-folder-1",
        "name": "The solo folder in this collection",
        "item": [] // blank array indicates this is a folder
    }]
}); // create a collection with an empty folder
// add a request to "my-folder-1" that sends a GET request
myCollection.items.one("my-folder-1").add(new Item({
    "name": "Send a GET request",
    "id": "my-get-request"
    "request": {
        "url": 'https://postman-echo.com/get",
        "method": "GET"
    }
}));`

We have an ItemGroup and then a blank item array.
So `myCollection.items.one("my-folder-1").add(new Item({` 
should be `myCollection.items.one("my-folder-1").items.add(new Item({`
1) Traverse top level where ItemGroup and Item reside
2) Find by id
3) Get the items prop for that item
4) Then call add to add another item

**Comment by kunagpal** [comment]
@georgejdli We've made improvements to our docs to address all such issues, I'm marking this closed. 😄
