### ISSUE TITLE
Collection Runner not loading

### ISSUE THREAD

**Issue by ButterNuts** [postmanlabs/postman-collection#488]
Version 5.3.1
OS X 14.5.0 / x64

Collection Runner is stalling out.  Unable to run collection
When I attempt to run a collection of tests, the collection window pops but then goes blank.  Attached screen shot. 

![screen shot 2017-10-20 at 10 42 20 am](https://user-images.githubusercontent.com/32964054/31832237-80ba34c8-b583-11e7-966d-3d4f371d90e6.png)

**Comment by kunagpal** [comment]
@ButterNuts Please open an issue [here](https://github.com/postmanlabs/postman-app-support/issues/new) if this persists on v5.3.2 of the Postman app.
