### ISSUE TITLE
Pre request script : be able to choose order of execution

### ISSUE THREAD

**Issue by mbetard-squid** [postmanlabs/postman-collection#490]
When executing a pre request script I do 2 things : 
```  
{
 postman.setGlobalVariable("text",data.text)
encryption part
} 
```
The encryption parts enables me to communicate with the server I need to test by encrypting the body (json) with a signature.

When I execute the POST request it firsts encrypt the body (generate a signature) then change the body. As a consequence the signature sent is always the same (before setting the text variable) and I am always forbidden to communicate with the server.

How can I be sure that it first set the variable then encrypt the body ?

**Comment by shamasis** [comment]
Can you report this in postman-app-support repository. This repository is for postman collection sdk.
