### ISSUE TITLE
How to Save automatically request and response in local  file  collection in postman

### ISSUE THREAD

**Issue by ajaykumar53123** [postmanlabs/postman-collection#52]
we are running the postman collection we would like to save all the request and response in local file

**Comment by kunagpal** [comment]
@ajaykumar53123 Apologies for the delay, please check out the following:

- For the Postman Clients, go to `Runner` in the top left corner, and from the list of previous collection runs on the left, select `Export as JSON` from the drop down arrow.
- For Newman, check out [Newman reporters](https://github.com/postmanlabs/newman#configuring-reporters)
