### ISSUE TITLE
Issue with order of requests excecuted when running a single folder

### ISSUE THREAD

**Issue by amirw1974** [postmanlabs/postman-collection#522]
im using the latest version of Postman (v5.3.2)
When running a folder that contains more than two requests it is not running the requests in the same order they appear in the main app
When running the all collection that contains the folder the order is ok

**Comment by shamasis** [comment]
Ok. Will look into it. However, I strongly recommend to drop a line about this in postman-app-support github repo or community.getpostman.com to get more eyes on the problem.

**Comment by shamasis** [comment]
Can you report this in postman-app-support repository. This repository is for postman collection sdk.
