### ISSUE TITLE
The `sample response` DOM can't scroll?

### ISSUE THREAD

**Issue by l19861225q** [postmanlabs/postman-collection#530]
Hi, one of my APIs `sample response` code DOM-height is higher than it's wrapper DOM, but I can't scoll the wrapper DOM to see more code... (Mac OSX + Chrome@63.0.3239.84)

![postman-issue_sample-response-can-not-scroll](https://user-images.githubusercontent.com/4251365/33920166-74d09cbc-dff7-11e7-9956-48cef8ca3f03.gif)

**Comment by mfoote** [comment]
Updating to version 6 allows you to sue 2 pane view

**Comment by shamasis** [comment]
Can you report this in postman-app-support repository if you still have issues. This repository is for postman collection sdk.
