### ISSUE TITLE
Postman link checker.

### ISSUE THREAD

**Issue by oabdelsamad** [postmanlabs/postman-collection#531]
Hi all, 

Not sure if it's the right place to ask about this. So I am using postman link checker (http://blog.getpostman.com/2017/06/23/check-for-broken-links-on-your-website-using-a-postman-collection/) and I do not want it to crawl all links on x page. How can I do so?  Is there any recursion-level so I can tell if I want a full crawler for the site or only on one page? If not, then it would be really good feature to have. 

Thank you in advance.

**Comment by shamasis** [comment]
Can you report this in postman-app-support repository. This repository is for postman collection sdk.
