### ISSUE TITLE
Request working in curl but not in postman

### ISSUE THREAD

**Issue by astraydog** [postmanlabs/postman-collection#541]
I copied the request  from GENERATE CODE SNIPPETS of CURL,it is working in curl.
`curl -X POST \
  http://xxx.xxx.xxx.xxx:9911 \
  -H 'Cache-Control: no-cache' \
  -H 'Postman-Token: f9b03f77-1f22-b90a-dcb4-12b67db281d3' \
  -d 'data={"dspid":"xxxx" , "timestamp":1488787766, "sign":"xxxxx", "code":110}'`
![curl](https://user-images.githubusercontent.com/2909868/34556994-b09b8170-f173-11e7-9f8a-5ab200fb3957.jpg)

but when I press  Send button in postman,the request is not working.
![postman-ui](https://user-images.githubusercontent.com/2909868/34557000-b64f7702-f173-11e7-920f-d10a2506b912.jpg)

**Comment by shamasis** [comment]
Can you report this in postman-app-support repository. This repository is for postman collection sdk.
