### ISSUE TITLE
How to clear current OAuth details ?

### ISSUE THREAD

**Issue by tushar4monto** [postmanlabs/postman-collection#583]
Hello
I am using Postman Desktop Application. Its working fine but there is one issue with OAuth 1.0 Authentication data. when all field are filled .like consumer key, consumer secret, token, token secret,

When I switch to other project API I want to clear current auth details. in your chome postman extension, there is one button for clear current auth data. I want to do same things in Postman desktop application, How can I do this? Please check below link for more information.

http://prntscr.com/ihssgv
http://prntscr.com/ihsvvf

Thanks

**Comment by shamasis** [comment]
Can you report this in postman-app-support repository. This repository is for postman collection sdk.

**Comment by tushar4monto** [comment]
Please provide the link of postman-app-support repository if possible 

Thank you
