### ISSUE TITLE
PropertyBase constructor uses the "info" property on definition

### ISSUE THREAD

**Issue by kbuzby** [postmanlabs/postman-collection#586]
The PropertyBase constructor checks for the ["info" property](https://github.com/postmanlabs/postman-collection/blob/270ed3df11995ea661bc6e1b774cdb432b10ff1d/lib/collection/property-base.js#L27) on the definition object passed in. However, the [type definition](https://github.com/postmanlabs/postman-collection/blob/270ed3df11995ea661bc6e1b774cdb432b10ff1d/lib/collection/property-base.js#L9) of PropertyBase only has a "description" property listed.

Looking at Property class it actually seems like these aren't in conflict - the constructor just takes a parameter that is either PropertyBase\~definition or an object with an info property that is of type PropertyBase~definition.

Is that correct? If so, can the documentation be updated?

**Comment by shamasis** [comment]
That’s correct. It’s supported in both as a side effect of inheritance. Though we intended it to be used as documented.
