### ISSUE TITLE
Property constructor uses definition object to check disabled property

### ISSUE THREAD

**Issue by kbuzby** [postmanlabs/postman-collection#587]
In the Property constructor the disabled property is looked for on the definition object which is passed as a parameter. If the object passed as a parameter has an info property this is used as the definition and stored in variable ["src"](https://github.com/postmanlabs/postman-collection/blob/270ed3df11995ea661bc6e1b774cdb432b10ff1d/lib/collection/property.js#L46). However, the disabled property is still [looked for](https://github.com/postmanlabs/postman-collection/blob/270ed3df11995ea661bc6e1b774cdb432b10ff1d/lib/collection/property.js#L87) on the definition object not the src object. 

Is it correct that the object getting passed as the definition parameter can be:
```
{
  info: { id, name}
  disabled
}
```
Which makes the info property not match the Property\~Definition type.

**Comment by shamasis** [comment]
@kamalaknn

**Comment by shamasis** [comment]
Yeah... that's a good catch @kbuzby. I went back and forth on this. Realised that looking into `src` is a sort of workaround to have a common prototype for supporting collection as well as folders (item group.)

This translates to:
- collection does not have official support for disabled property :-p
- collection is the only object documented to support .info property.
- as such we do not need to make any change.

But I do get why this would be confusing. @kamalaknn can we document this behaviour where we are choosing the `src` variable?

Also @kbuzby, the schema is another type reference: https://schema.getpostman.com/json/collection/v2.1.0/docs/index.html
