### ISSUE TITLE
Description~definition format vs type

### ISSUE THREAD

**Issue by kbuzby** [postmanlabs/postman-collection#592]
Description\~definition says that there is a ("format")[https://github.com/postmanlabs/postman-collection/blob/270ed3df11995ea661bc6e1b774cdb432b10ff1d/lib/collection/description.js#L38] property; however, the Description class uses the "type" property.

Should the "format" property in the typedef be updated to "type"?

**Comment by shamasis** [comment]
@kamalaknn

**Comment by shamasis** [comment]
Just checked schema at https://schema.getpostman.com/json/collection/v2.1.0/docs/index.html

- type is correct
- we need to fix jsdoc bug @kamalaknn
