### ISSUE TITLE
Initial request became edited after edit of its duplicate in Postman 6.0.7 for Win

### ISSUE THREAD

**Issue by serg1409** [postmanlabs/postman-collection#595]
Steps:
1. Make a duplicate of a saved collection request in Postman 6.0.7 for Win
2. Start edit the new request
3. Initial request (body and tests) became edited along with the new one

It didn't happen in Postman 5.
I had to go back to Postman 5.5.3

**Comment by shamasis** [comment]
Can you report this in postman-app-support repository. This repository is for postman collection sdk.
