### ISSUE TITLE
Feature request: Make environment variables persistent

### ISSUE THREAD

**Issue by aprixon01112017** [postmanlabs/postman-collection#601]
I have a huge collection of requests organized in folders. The API that is tested needs logging in (JWT). So I have to use the returned token in subsequent requests.

I want to manually and selectively run a login request and then any single other request in that folder without running the whole collection or folder.

The login requests writes the token into a env variable and subsequent requests use it.

It would be nice to have the env variable with the token persistent for tha reason

**Comment by shamasis** [comment]
Can you report this in postman-app-support repository. This repository is for postman collection sdk.
