### ISSUE TITLE
Collection runner not collecting responses

### ISSUE THREAD

**Issue by orestes** [postmanlabs/postman-collection#604]
Postman version `v6.0.9`.
Operating System: `Mac OS X`

Steps to reproduce

* Open the Collection Runner
* Select a collection
* Make sure `Log Responses` is set to `For all requests`
* Run the collection

Expected result

* Individual requests can be inspected and the response body is available for debugging

Actual result

* Response body is always missing and the following message is displayed: `Data unavailable (only data about the top 10 historical runs is stored)`

![screen shot 2018-03-14 at 01 28 17](https://user-images.githubusercontent.com/618107/37376903-00aff40a-2727-11e8-88ca-0762b08be772.png)

**Comment by shamasis** [comment]
Can you report this in postman-app-support repository. This repository is for postman collection sdk.
