### ISSUE TITLE
Request - Response: addQueryParams & addHeader Issues

### ISSUE THREAD

**Issue by thomGeenen** [postmanlabs/postman-collection#631]
Hi everybody ! 

Little issue about postman-collection.

When I use the "addQueryParams" function, I receive no error if I'm not using a .catch.

When I use the ".catch", they give me an error for every routes i've.

I've tried to add the parameters in the tabs/array by pushing, adding, inserting & appending but no one of theses solutions works.. 

Could you help me ?

Here are the code 

`
var pmCollection = new Collection({
            info: {
                name: schema.document.info.name,
                version: schema.document.info.version
            },
            variable: schema.document.variable,
            auth: requestAuth,
            event: event
        });

        
        var itemGroup;
        for (var rs in RequestService.routes) {
            var r = RequestService.routes[rs];

            var item = new Item({
                "name": rs
            });

            try {

                var request = new Request({
                    "url": {
                        "raw": "{{url}}" + rs.split(" ")[1],
                        "host": ["{{url}}"],
                        "path": rs.split(" ")[1].split("/")
                    },
                    "method": rs.split(" ")[0],
                    "description": ""
                });

                if (Object.keys(r.query).length !== 0) {
                    for (const key in r.query) {

                        var formParams = new FormParams({
                            key: key.toString(),
                            value: r.query[key].toString()
                        });
                        request.addQueryParams(formParams).catch((err) => {
                            sails.log(err);
                        })
                    }
                }

                if (r.in) {
                    request.body = {
                        mode: "raw",
                        raw: getExampleFromJson(r.in, true)
                    }

                    request.addHeader({
                        key: schema.document.headers.json.key.toString(),
                        value: schema.document.headers.json.value.toString()
                    }).catch((err) => {
                        sails.log(err);
                    })
                    request.description += getDocumentationFromJson(r.in);
                }
                if (r.policy) {
                    
                    request.addHeader({
                        key: schema.document.headers.auth.key,
                        value: schema.document.headers.auth.value
                    }).catch((err) => {
                        sails.log(err);
                    })
                }

                if (request.url.raw == "{{url}}/api/v1/auth/generate" || request.url.raw == "{{url}}/api/v1/auth/refresh") {
                    item.events = event
                }

                item.request = request;

                var response = new Response({
                    name: rs,
                    originalRequest: request,
                    status: "ok",
                    code: 200,
                    "_postman_previewlanguage": "json",
                    header: [],
                    cookie: []
                });

                if (r.out) {
                    response.body += getExampleFromJson(r.out, true);
                }

                item.responses = response;

                var groupName = rs.split(" ")[1].split('/')[3];

                if(itemGroup && itemGroup.name){
                    itemGroup.items.insert(item);
                }
                else{
                    itemGroup = new ItemGroup({
                        name: groupName,
                        auth: requestAuth,
                        event: event
                    })
                }   

                pmCollection.items.add(itemGroup);

            } catch (error) {
                sails.log(`Error when defining ${rs}`);
            }

        }
        
        

        fs.writeFile("postman_collection.json", JSON.stringify(pmCollection), (success, error) => {
            
            if(success) return console.log(success);
            if(error) return console.log(error);
        });`

here are the errors :

![capture d ecran 2018-05-02 a 09 16 58](https://user-images.githubusercontent.com/32299073/39510334-b0c93e94-4de9-11e8-8de7-59c2025b5968.png)

Thank you for helping me

**Comment by shamasis** [comment]
It's been a while on this issue. Since it does not seem to be a bug, closing it.
