### ISSUE TITLE
Collection version 2.1 is not backwards compatible with 2.0

### ISSUE THREAD

**Issue by creichert** [postmanlabs/postman-collection#635]
I'm trying to understand some changes made to Postman Collection version 2.1 that I believe are backwards incompatible.

It seems as though collection auth now take arrays instead of objects:

- **v2.0**
    ![collection auth v2.0 basic auth](https://user-images.githubusercontent.com/526560/39777342-f20f8ab4-52c8-11e8-96fc-b64368ec65a6.png)

- **v2.1**
    ![collection auth v2.1](https://user-images.githubusercontent.com/526560/39777555-7ec4ffca-52c9-11e8-9cbe-f78a274b4b12.png)

As a service provider that integrates and attempts to maintain compatibility w/ Postman Collections, this means our parser is broken because we coded against 2.0. Making a change in our code to handle this specific scenario is not difficult to implement, but it's not clear whether a similar change might have been made to other areas of the schema without making a direct comparison or every field.

I think this problem is made worse due to `info.version` being an optional field. I can't check the version and explicitly white-list only `v2.0` or determine if a future `v2.*` version might be compatible or not. It's possible other fields might have similar breaking changes in `v2.2`.

---

Related PRs:
- https://github.com/postmanlabs/postman-collection/pull/447
- https://github.com/postmanlabs/postman-collection/pull/446

It seems as though the JavaScript code in this repo handles the variance implicitly (https://github.com/postmanlabs/postman-collection/pull/446/files#diff-59d7d9b410c9cddfd7951b18cdf828ebR89). It can parse an array or object but always outputs an array.

---

APIMatic alludes to the same issue here: https://docs.apimatic.io/changelog/support-for-postman-v21-added/

>  This new format has changes related to how authentication is described as compared to how it was described in Postman v.2.0.

**Comment by creichert** [comment]
I could definitely be misunderstanding something here. If so, please let me know! We are making the change to our code to handle both cases but I want to ensure that we don't have this problem in the future (whether I am misunderstanding the compatibility or not).

Thanks!

**Comment by shamasis** [comment]
@kunagpal - can you check.

**Comment by kunagpal** [comment]
@creichert Yes, this was done to make auth helper definitions more comprehensive. In general, v2.1 is different from v2.0 in the following ways:
1. Auth helpers are an array instead of an object.
2. Request URLs are always an object, while they were objects or strings in v2.0.

**Comment by creichert** [comment]
@kunagpal Thanks, I understand why the change was made.

My complaint is that **the minor version bump to v2.1 is incorrect under SEMVER** and this breaks external tools.

> Auth helpers are an array instead of an object.

This is a **breaking change** under SEMVER and **not backwards compatible**. The version should have been bumped to v3.0. My understanding is that the [Postman Collection format follows SEMVER]( https://github.com/postmanlabs/postman-collection/blob/645b4deaceb009c914a942fb4bcb219d65737ee3/lib/collection/collection.js#L33).

---

Additionally, please consider making `info.version` a required field. From my original question:

> I think this[backwards incompatible] problem is made worse due to info.version being an optional field. I can't check the version and explicitly white-list only v2.0 or determine if a future v2.* version might be compatible or not. It's possible other fields might have similar breaking changes in v2.2.

**Comment by kunagpal** [comment]
@creichert Sorry for the delayed response, but the collection schema versions do not follow the semver standard strictly at the moment. As such, minor version bumps may contain breaking changes, while major version bumps will always contain breaking changes. I agree that this could be documented better, though 😄

**Comment by creichert** [comment]
@kunagpal No worries, we've implemented the change without a huge disturbance. Do you think it's possible to require the info.version in the future?
