### ISSUE TITLE
Not able to import a JSON/CSV file while creating tests in postman

### ISSUE THREAD

**Issue by mvaranasi123** [postmanlabs/postman-collection#637]
i am using postman for the first time, i want to write a script to validate my response against my data in XL file. Can any one help me to import the file or what could be wrong which is causing the error" format not recognized" all the times while importing JSON/CSV files /pasting as raw text.

Any input on this helps!

**Comment by shamasis** [comment]
Can you report this in postman-app-support repository. This repository is for postman collection sdk.
