### ISSUE TITLE
Why Collection Runner rounding de number for option data

### ISSUE THREAD

**Issue by michelics** [postmanlabs/postman-collection#638]
I tried run a collection by Collection Runner, using a Data option with json file.

See file position 5:

![image](https://user-images.githubusercontent.com/15693278/39930576-772e666c-5511-11e8-9fd9-46a3d0d0da64.png)

See the preview:

![image](https://user-images.githubusercontent.com/15693278/39930639-a5783746-5511-11e8-98ad-ff40606e5dae.png)

**Comment by shamasis** [comment]
Can you report this in the postman-app-support repository. This module is for collection SDK
