### ISSUE TITLE
Status code is 200 | TypeError: Cannot read property 'to' of undefined.

### ISSUE THREAD

**Issue by karthikkashi9** [postmanlabs/postman-collection#676]
My tests are failing with Status code is 200 | TypeError: Cannot read property 'to' of undefined at collection level. I have defined a global variable

**Comment by codenirvana** [comment]
@karthikkashi9 Can you please elaborate?

**Comment by shamasis** [comment]
This issue needs more details and seems that we can close it for lack of activity. We couldn’t reproduce it with the details at hand. Please comment to reopen with more info to reproduce. It would help us a lot.
