### ISSUE TITLE
Capturing API requests, target collection shows wrong requests counts.

### ISSUE THREAD

**Issue by mechbullgt** [postmanlabs/postman-collection#697]
I'm trying to capture API requests but the target collection shows requests count for even an empty collection.

Please find below screenshot for the same.
![emptycollection_shows_count](https://user-images.githubusercontent.com/23336355/44853432-9bd63480-ac83-11e8-8dbb-fb8b5e68ac66.png)

**Comment by codenirvana** [comment]
@mechbullgt Thanks for reporting this issue.

We are tracking all the app related issues at [postman-app-support](https://github.com/postmanlabs/postman-app-support/issues) issue tracker. Can you move this issue there with all the required details?
