### ISSUE TITLE
Value of Environment, Global and local Variable set within a function is only available when test terminates

### ISSUE THREAD

**Issue by PeeEmMee** [postmanlabs/postman-collection#704]
Based on the quick reference guide, to get around reference is define a variable prior to using it in a function or creating a global variable then 'setting' it within the function. See screenshot below of quick guide:
![image](https://user-images.githubusercontent.com/43204973/45420044-33547200-b6dd-11e8-9f1c-96515ceea4e8.png)

In the screenshot below, I created an environment, global and local variable and set it with a string so I know if did change or not. I then 'set' them within the function used by pm.sendrequest with the value from response.json(). After pm.sendrequest block, I found out that variables did not change at all. 
![image](https://user-images.githubusercontent.com/43204973/45420359-10768d80-b6de-11e8-8ef8-dcb92e0f9254.png)

I might be doing something wrong. I'm running out of option and I'm thinking of writing the response to a file so I can use it outside pm.sendrequest block.

My Postman version is  v6.3.0.

**Comment by codenirvana** [comment]
@PeeEmMee `pm.sendRequest` sends requests asynchronously, that's why initial values are logged first.
To access the updated values you need to move your code inside the `sendRequest` callback.
Like:
```javascript
pm.sendRequest('https://postman-echo.com/get', function (err, res) {
  if (err) { console.log(err); }
  pm.test('response should be okay to process', function () {
    pm.expect(err).to.equal(null);
    pm.expect(res).to.have.property('code', 200);
    pm.expect(res).to.have.property('status', 'OK');
  });
  // Your code goes here...
});
```

**Comment by PeeEmMee** [comment]
Thanks @codenirvana. 

That's means moving the rest of my code (around 200 lines) within that block. Is there no other way to do this better?

**Comment by PeeEmMee** [comment]
I'm going down that path of writing the response to a file but I'm stuck again. Writing a code to do this is not supported at the moment. You have to click on send and download :-(

**Comment by codenirvana** [comment]
@PeeEmMee You can wrap your code in a function and call that from the `sendRequest` callback.
Or, why not move this to a separate request?

**Comment by PeeEmMee** [comment]
@codenirvana the response from the current request is used to drive pm.sendrequest. I then do a comparison between the two responses. I don't prefer populating environment variables and 'setting' next request then going back to the current request. Feels like spaghetti workflow to me. 

The quick reference guide was my basis that it should be possible to access the environment, global or local variables as long as you declare/define it outside of the function. Is this a limitation in Postman or not really possible? Is the quick reference guide official doc from postman?

**Comment by codenirvana** [comment]
@PeeEmMee The [quick reference guide](https://community.getpostman.com/t/the-postman-cheatsheet-quick-reference-guide/1054) is not published officially from Postman.

It's not a limitation, this is the asynchronous nature of JavaScript. `pm.sendRequest` sends requests asynchronously and calls the callback function once the request is ended, which means your code(outside the callback) will also get executed before the request ends and that's the reason initial values are logged first even before making the `pm.sendRequest` call.

**Comment by PeeEmMee** [comment]
Thanks @codenirvana 

pm is an object provided by postman. I still think that it should have been designed better.
