### ISSUE TITLE
How do I merge 2 collections ?

### ISSUE THREAD

**Issue by chan4lk** [postmanlabs/postman-collection#718]
var fs = require('fs'),
    Collection = require('postman-collection').Collection,
    myCollection;

    myCollection = new Collection({
    info: {
        name: "my Collection"
    }
});

var userToken = new Collection(JSON.stringify(fs.readFileSync('./Collections/UserToken/UserToken.postman_collection.json').toString()));
var products = new Collection(JSON.stringify(fs.readFileSync('./Collections/OtherCollections/GetProducts.postman_collection.json').toString()));

userToken.items.each(item => myCollection.items.add(item));
products.items.each(item => myCollection.items.add(item));

// log the collection to console to see its contents
fs.writeFileSync('myCollection.postman_collection', JSON.stringify(myCollection, null, 2));

Tried above code. But it's not working

**Comment by codenirvana** [comment]
While creating a collection instance from file read, do JSON.parse instead of JSON.stringify.
```js
var userToken = new Collection(JSON.parse(fs.readFileSync('collection.json').toString()));
```
