### ISSUE TITLE
How to create a collection?

### ISSUE THREAD

**Issue by elieobeid7** [postmanlabs/postman-collection#764]
The docs talk about how to edit an existing collection, but assuming I don't have an existing collection, how to create one?

The very first example in the docs, getting started

http://www.postmanlabs.com/postman-collection/

`In this example snippet we will get started by loading a collection from a file and output the same in console.`

So they start by assuming the existence of a collection. I want to generate one, how to do so?

**Comment by codenirvana** [comment]
@elieobeid7 You can either pass an existing collection JSON or define everything from the scratch.
A detailed documentaion is available here: http://www.postmanlabs.com/postman-collection/
Collection schema documentation: https://schema.getpostman.com/

Example:
```javascript
const
    sdk = require('postman-collection'),
    Item = sdk.Item,
    Request = sdk.Request,
    ItemGroup = sdk.ItemGroup,
    Collection = sdk.Collection;

let
    // define two Requests
    request1 = new Request({
        url: 'https://postman-echo.com/post',
        method: 'POST'
    }),
    request2 = new Request({
        url: 'https://postman-echo.com/get',
        method: 'GET'
    }),

    // define two Items using the Requests
    item1 = new Item({
        name: 'First Item',
        request: request1
    }),
    item2 = new Item({
        name: 'Second Item',
        request: request2
    }),

    // define ItemGroup from Items
    itemGroup = new ItemGroup({
        name: 'Folder 1',
        item: [item1, item2]
    }),

    // define a Collection
    collection = new Collection({
        info: {
            name: 'New Collection'
        },
        item: [itemGroup]
    });
```
