### ISSUE TITLE
How to create new collection from existing collection file

### ISSUE THREAD

**Issue by wonboyn** [postmanlabs/postman-collection#847]
Hi there,

I have an existing collection I've exported from Postman. The existing superset collection has the requests sitting in nested folders (item groups?)

I'd like to be able to programatically create new collections that are subsets of the original superset collection to allow testing of certain modules. 

I've followed the examples in the [doco](https://www.postmanlabs.com/postman-collection/index.html) but am struggling to understand how to iterate through the item groups.

I can load my collection file & get the top level items groups (myCollection.items), but cannot see how to get &/or iterate through the child objects from there.

Any help / examples / documentation would be greatly appreciated.

Thanks

Tim

**Comment by codenirvana** [comment]
@wonboyn As you mentioned, the complete documentation is available here: https://www.postmanlabs.com/postman-collection/index.html

For your particular use case, item groups are of type [PropertyList](https://www.postmanlabs.com/postman-collection/PropertyList.html).
You can use methods like `PropertyList#each` or `PropertyList#eachParent` to traverse the items in a Postman Collection.
