### ISSUE TITLE
version control for collection extremely difficult (leads to corrupt collections while merging)

### ISSUE THREAD

**Issue by bhonnegowda** [postmanlabs/postman-collection#85]
collection gets corrupted while merging if there more than a few conflicts to resolve. 
Tip: maybe simplify how the collections are generated across different versions of postman.

**Comment by czardoz** [comment]
@bhonnegowda do open an issue on our issue tracker: https://github.com/postmanlabs/postman-app-support/issues

This issue tracker is meant for bugs related to the postman-collection Javascript library :smiley:
