### ISSUE TITLE
Unable to update environment variable on Environment quick view mode

### ISSUE THREAD

**Issue by venkataramkishore** [postmanlabs/postman-collection#861]
After update v7.0.9, I am unable to quickly update the environment variable(s) in (Environment quick look ) quick view mode. I have to explicit change the value via setting.

**Comment by venkataramkishore** [comment]
When I try to change one of the value in Environment quick look mode, new value also reflects on the second next property value from the current change value. 
1 field1 value1
2 field2 value2
3 field3 value3

In the above case, if I change the value of field1 then new value1 also reflects on value3

**Comment by codenirvana** [comment]
@venkataramkishore Please file your issue at https://github.com/postmanlabs/postman-app-support/issues
This repository is specific to Postman Collection SDK.
