### ISSUE TITLE
SDK links doc broken

### ISSUE THREAD

**Issue by sellomkantjwa** [postmanlabs/postman-collection#923]
The linked SDK docs link, [Collection SDK Docs](http://postmanlabs.com/postman-collection) is broken

**Comment by codenirvana** [comment]
@sellomkantjwa Thanks for reporting this issue.
Looks like it's not redirecting to `www.postmanlabs.com`.

**Comment by sellomkantjwa** [comment]
Actually looks like this is backwards. www.postmanlabs.com redirects to postmanlabs.com
![image](https://user-images.githubusercontent.com/5308286/62037826-d67a8100-b1f4-11e9-8bc6-aed3f78d9fc5.png)

**Comment by csk1827** [comment]
I think this issue can be closed now!
