### ISSUE TITLE
Iteration index is not increased in collection running as in json data file

### ISSUE THREAD

**Issue by hungdao-testing** [postmanlabs/postman-collection#982]
**#### Precondition:**
- Have a Json file 
```[
  {
    "requestName": "Get a single booking",
    "bookingId": 1,
    "expectResponse": {
      "firstname": "Sally",
      "lastname": "Jones",
      "totalprice": 992,
      "depositpaid": false,
      "bookingdates": {
        "checkin": "2015-04-17",
        "checkout": "2018-03-29"
      }
    }
  },
  {
    "requestName": "Get a bulk booking",
    "bookingId": 2,
    "expectResponse": {
      "firstname": "Mary",
      "lastname": "Jones",
      "totalprice": 890,
      "depositpaid": true,
      "bookingdates": {
        "checkin": "2015-08-21",
        "checkout": "2016-09-29"
      }
    }
  }
]
```

- Have a list of requests "Get a single booking", "Get a bulk booking" inside a folder "Get a single booking",
- The request "Get a single booking" has
-- URL: {{baseURL}}/booking/{{bookingId}}

**#### Procedure:**
- In folder, I configure as following
-- Pre-request script: 
`
let requestName = pm.iterationData.get("requestName");
postman.setNextRequest(requestName)`
The purpose is each iteration will call the specific request_name, and assert the corresponding data

- Run the collection with the json file

**#### Expected result:**
- With each iteration, the corresponding request is called 

**#### Actual result:**
- The iteration variable is always 0, not increasing.

**Comment by jainpawan21** [comment]
Can you explain more? I am not getting your issue.

**Comment by hungdao-testing** [comment]
Please close this bug. It seems something wrong in my configuration
